### PR TITLE
don't mangle decorators on processing

### LINKED ISSUE #35: Sickle chokes on decorators (likely due to a bug in TS < 1.8)
Input:
```javascript
class DecoratorTest {
  @foo
  private x: number;

  constructor() {}
}
```
causes a crash due to a failed assertion about offsets.

With some debugging, I found that the resulting syntax tree when parsing this input is bogus.  Note how the AtToken shows up twice.

```
| | | | node: PropertyDeclaration
| | | | | node: AtToken
| | | | | node: SyntaxList
| | | | | | node: Decorator
| | | | | | | node: AtToken
| | | | | | | node: Identifier
| | | | | node: SyntaxList
| | | | | | node: PrivateKeyword
| | | | | node: Identifier
```

Upgrading our TypeScript dep to typescript@beta (1.8) produces

```
| | | | node: PropertyDeclaration
| | | | | node: SyntaxList
| | | | | | node: Decorator
| | | | | | | node: AtToken
| | | | | | | node: Identifier
| | | | | node: SyntaxList
| | | | | | node: PrivateKeyword
| | | | | node: Identifier
```

which is a layout I expect.

### PR DESCRIPTION
**Pull request by martine**
There were two issues:
1) TypeScript <1.8 has a busted parse of decorators (see bug for
   an example), so update to TS 1.8;
2) We stripped comments when emitting "private" to avoid a Closure
   issue but doing so also stripped preceding whitespace, which
   meant that in a line like "@foo private bar" there would be no
   space between "@foo" and "private" in the output.  Fix this by
   being more careful about emitting whitespace.

Fixes #35.

### CODE REVIEW

File: test_files/sickle/parameter_properties.ts [hunk 1]
```diff
@@ -1,6 +1,8 @@
 class ParamProps {
   // The @export below should not show up in the output ctor.
-  constructor(public bar: string,public bar2: string) {
+  constructor(
+public bar: string,
+public bar2: string) {
```
Comment (martine) [inline test_files/sickle/parameter_properties.ts]: I'm not super happy that sickle munges this but I don't care *too* much.

File: src/sickle.ts [hunk 2]
```diff
@@ -222,7 +222,16 @@ class Annotator {
   private writeNode(node: ts.Node, skipComments: boolean = false) {
     if (node.getChildCount() == 0) {
       // Directly write complete tokens.
-      this.emit(skipComments ? node.getText() : node.getFullText());
+      if (skipComments) {
+        if (node.getFullStart() < node.getStart()) {
+          // Emit a space to replace the comment, as the comment served
```
Comment (rkirov) [inline src/sickle.ts]: emit a newline

File: src/sickle.ts [hunk 3]
```diff
@@ -222,7 +222,16 @@ class Annotator {
   private writeNode(node: ts.Node, skipComments: boolean = false) {
     if (node.getChildCount() == 0) {
       // Directly write complete tokens.
-      this.emit(skipComments ? node.getText() : node.getFullText());
+      if (skipComments) {
+        if (node.getFullStart() < node.getStart()) {
```
Comment (rkirov) [inline src/sickle.ts]: Maybe extract into a helper function - `nodeHasAComment`, seems useful and not totally obvious from the node api

File: test/test_support.ts [hunk 4]
```diff
@@ -12,6 +12,7 @@ const OPTIONS: ts.CompilerOptions = {
   noResolve: true,
   skipDefaultLibCheck: true,
   noEmitOnError: true,
+  experimentalDecorators: true,
```
Comment (rkirov) [inline test/test_support.ts]: another option to add here is `emitDecoratorMetadata`, to match our internal TS flags.

File: test_files/sickle/parameter_properties.ts (hunk 1 above)
Comment (rkirov) [inline test_files/sickle/parameter_properties.ts]: agree, we have bigger fish to fry :)

**Comment by rkirov** [comment]
LGTM

File: src/sickle.ts (hunk 3 above)
Comment (martine) [inline src/sickle.ts]: Unfortunately this doesn't actually check for a comment, so it feels wrong to pull it into a function.  I will add a comment and a TODO.

File: test/test_support.ts (hunk 4 above)
Comment (martine) [inline test/test_support.ts]: It looks like that depends on this flag being also set.  I added it.
